# Step 1: Nginx ke lightweight alpine version ko base image chunein
FROM nginx:alpine

# Step 2: Apni html file ko Nginx ke default hosting folder me copy karein
COPY index.html /usr/share/nginx/html/

# Step 3: Web server ke default Port 80 ko expose karein
EXPOSE 80
